// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/monitorables/pingdom/api/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCheck provides a mock function with given fields: checkID
func (_m *Repository) GetCheck(checkID int) (*models.Check, error) {
	ret := _m.Called(checkID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheck")
	}

	var r0 *models.Check
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Check, error)); ok {
		return rf(checkID)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Check); ok {
		r0 = rf(checkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(checkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChecks provides a mock function with given fields: tags
func (_m *Repository) GetChecks(tags string) ([]models.Check, error) {
	ret := _m.Called(tags)

	if len(ret) == 0 {
		panic("no return value specified for GetChecks")
	}

	var r0 []models.Check
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Check, error)); ok {
		return rf(tags)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Check); ok {
		r0 = rf(tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionCheck provides a mock function with given fields: checkID
func (_m *Repository) GetTransactionCheck(checkID int) (*models.Check, error) {
	ret := _m.Called(checkID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionCheck")
	}

	var r0 *models.Check
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Check, error)); ok {
		return rf(checkID)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Check); ok {
		r0 = rf(checkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(checkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionChecks provides a mock function with given fields: tags
func (_m *Repository) GetTransactionChecks(tags string) ([]models.Check, error) {
	ret := _m.Called(tags)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionChecks")
	}

	var r0 []models.Check
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Check, error)); ok {
		return rf(tags)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Check); ok {
		r0 = rf(tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
