// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	options "github.com/monitoror/monitoror/service/options"
	mock "github.com/stretchr/testify/mock"
)

// RouterOption is an autogenerated mock type for the RouterOption type
type RouterOption struct {
	mock.Mock
}

// Apply provides a mock function with given fields: s
func (_m *RouterOption) Apply(s *options.RouterSettings) {
	_m.Called(s)
}

// NewRouterOption creates a new instance of RouterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouterOption {
	mock := &RouterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
