// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/github"

	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// Issues provides a mock function with given fields: ctx, query, opt
func (_m *SearchService) Issues(ctx context.Context, query string, opt *github.SearchOptions) (*github.IssuesSearchResult, *github.Response, error) {
	ret := _m.Called(ctx, query, opt)

	if len(ret) == 0 {
		panic("no return value specified for Issues")
	}

	var r0 *github.IssuesSearchResult
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *github.SearchOptions) (*github.IssuesSearchResult, *github.Response, error)); ok {
		return rf(ctx, query, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *github.SearchOptions) *github.IssuesSearchResult); ok {
		r0 = rf(ctx, query, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.IssuesSearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *github.SearchOptions) *github.Response); ok {
		r1 = rf(ctx, query, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *github.SearchOptions) error); ok {
		r2 = rf(ctx, query, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewSearchService creates a new instance of SearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchService {
	mock := &SearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
