// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/monitorables/gitlab/api/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCountIssues provides a mock function with given fields: params
func (_m *Repository) GetCountIssues(params *models.IssuesParams) (int, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetCountIssues")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.IssuesParams) (int, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*models.IssuesParams) int); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.IssuesParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMergeRequest provides a mock function with given fields: projectID, mergeRequestID
func (_m *Repository) GetMergeRequest(projectID int, mergeRequestID int) (*models.MergeRequest, error) {
	ret := _m.Called(projectID, mergeRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequest")
	}

	var r0 *models.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*models.MergeRequest, error)); ok {
		return rf(projectID, mergeRequestID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *models.MergeRequest); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(projectID, mergeRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMergeRequestPipelines provides a mock function with given fields: projectID, mergeRequestID
func (_m *Repository) GetMergeRequestPipelines(projectID int, mergeRequestID int) ([]int, error) {
	ret := _m.Called(projectID, mergeRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequestPipelines")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]int, error)); ok {
		return rf(projectID, mergeRequestID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []int); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(projectID, mergeRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMergeRequests provides a mock function with given fields: projectID
func (_m *Repository) GetMergeRequests(projectID int) ([]models.MergeRequest, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequests")
	}

	var r0 []models.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.MergeRequest, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.MergeRequest); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipeline provides a mock function with given fields: projectID, pipelineID
func (_m *Repository) GetPipeline(projectID int, pipelineID int) (*models.Pipeline, error) {
	ret := _m.Called(projectID, pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for GetPipeline")
	}

	var r0 *models.Pipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*models.Pipeline, error)); ok {
		return rf(projectID, pipelineID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *models.Pipeline); ok {
		r0 = rf(projectID, pipelineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Pipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(projectID, pipelineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipelines provides a mock function with given fields: projectID, ref
func (_m *Repository) GetPipelines(projectID int, ref string) ([]int, error) {
	ret := _m.Called(projectID, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetPipelines")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]int, error)); ok {
		return rf(projectID, ref)
	}
	if rf, ok := ret.Get(0).(func(int, string) []int); ok {
		r0 = rf(projectID, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(projectID, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProject provides a mock function with given fields: projectID
func (_m *Repository) GetProject(projectID int) (*models.Project, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Project, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Project); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
