// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/monitorables/ping/api/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ExecutePing provides a mock function with given fields: hostname
func (_m *Repository) ExecutePing(hostname string) (*models.Ping, error) {
	ret := _m.Called(hostname)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePing")
	}

	var r0 *models.Ping
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Ping, error)); ok {
		return rf(hostname)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Ping); ok {
		r0 = rf(hostname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ping)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hostname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
