// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/models"
	mock "github.com/stretchr/testify/mock"
)

// Monitorable is an autogenerated mock type for the Monitorable type
type Monitorable struct {
	mock.Mock
}

// Enable provides a mock function with given fields: variantName
func (_m *Monitorable) Enable(variantName models.VariantName) {
	_m.Called(variantName)
}

// GetDisplayName provides a mock function with given fields:
func (_m *Monitorable) GetDisplayName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetVariantsNames provides a mock function with given fields:
func (_m *Monitorable) GetVariantsNames() []models.VariantName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVariantsNames")
	}

	var r0 []models.VariantName
	if rf, ok := ret.Get(0).(func() []models.VariantName); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VariantName)
		}
	}

	return r0
}

// Validate provides a mock function with given fields: variantName
func (_m *Monitorable) Validate(variantName models.VariantName) (bool, []error) {
	ret := _m.Called(variantName)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	var r1 []error
	if rf, ok := ret.Get(0).(func(models.VariantName) (bool, []error)); ok {
		return rf(variantName)
	}
	if rf, ok := ret.Get(0).(func(models.VariantName) bool); ok {
		r0 = rf(variantName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(models.VariantName) []error); ok {
		r1 = rf(variantName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// NewMonitorable creates a new instance of Monitorable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitorable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Monitorable {
	mock := &Monitorable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
